name: Build and test

on: [pull_request]

jobs:
  check-ubuntu-Dockerfile:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Docker build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./ci/ubuntu-Dockerfile
